<?php
$typeArr[1] = '博客';
$typeArr[2] = '作品';
$typeArr[3] = '图书';
$typeArr[4] = '工具';
$typeArr[5] = '影音';
$typeArr[6] = '交流';
$typeArr[7] = '娱乐';
$typeArr[8] = '工作';
$typeArr[9] = '我';
$typeArr[10] = '开发';
$typeArr[11] = '感悟心得';
$typeArr[12] = '已读图书';
$typeArr[13] = '计划读的书';
$typeArr[14] = '经验之谈';
$typeArr[21] = '小萌';
$typeArr[16] = '电影';
$typeArr[17] = '音乐';
$typeArr[18] = '开心一刻';
$typeArr[19] = '杂七杂八';
$typeArr[20] = '无关技术';
$typeArr[22] = '万年历';
$typeArr[23] = '相册';
$typeArr[24] = '自娱自乐';
?>