<?php
$z[0]=Array("global","",15,42);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("field","",42,63);
$z[1][4]['name']="typeurl";
$z[2]=Array("channel","\r\n                    <span><a href=\"[field:global.cfg_basehost/][field:typelink/]\">[field:typename/]</a></span>\r\n                ",121,370);
$z[2][4]['type']="son";
$z[2][4]['currentstyle']="<span><a href=";
$z[2][4]['~typeurl~" class']="active";
$z[2][4]['>~typename~</a></span>"']="";

?>