[field:b-typenum/]
                {/dede:sql]
            </p>
            <p>工具：
                {dede:type typeid=1}
                    [field:id function="GetTotalArc(@me)" /]
                {/dede:type}</p>
            <p>访问：46384</p>
        </div>
    </div><!-- count start -->
    <!-- 友好网站 start -->
    <div class="side">
        <div class="count-n">
            <div class="title clear-padding">
                友好网站
                <!-- <a href="{dede:global.cfg_basehost