<?php
$z[0]=Array("global","",161,189);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("arcurl","",189,204);
$z[2]=Array("title","",229,243);
$z[3]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<img src='{@me['litpic']}' />\"); ",275,384);
$z[3][4]['runphp']="yes";
$z[4]=Array("global","",454,482);
$z[4][4]['name']="cfg_basehost";
$z[5]=Array("arcurl","",482,497);
$z[6]=Array("title","",506,520);
$z[7]=Array("title","",538,552);

?>