<?php
$z[0]=Array("global","",396,424);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("arcurl","",424,439);
$z[2]=Array("title","",448,462);
$z[3]=Array("title","",480,494);
$z[4]=Array("description","",638,658);
$z[5]=Array("global","",697,725);
$z[5][4]['name']="cfg_basehost";
$z[6]=Array("arcurl","",725,740);
$z[7]=Array("title","",769,783);
$z[8]=Array("writer","",1021,1036);
$z[9]=Array("id function=gettags(@me)","",1165,1199);

?>