<!-- list start -->
                <div class="list">
                    <div class="detail clear-width">
                        <div class="title">
                            <h2>
                                <a href="[field:global.cfg_basehost/][field:arcurl/]" title="[field:title/]" target="_blank">[field:title/]</a>
                            </h2>
                        </div>
                        <div class="des">
                            [field:description/]
                            <a href="[field:global.cfg_basehost/][field:arcurl/]" class="go-on-ready" title="[field:title/]" target="_blank"><我还想看啊></a>
                        </div>
                        <div class="title">
                            <p class="info clear-text-align margin-top10">
                                <span>作者：[field:writer/]</span>
                                <span><a href="[field:typeurl/]">[field:typename/]</a></span>
                                <span>Tags：[field:id function=GetTags_list('@me')/]</span>
                                <span class="float-right">不看详细介绍了
								<a href="" class="go-on-ready" target="_blank"><直接下载></a>
                                </span>                                
                            </p>
                        </div>
                    </div>
                </div><!-- list end -->