<li id="nav-li-{dede:field name='id'/}">
        		<a href="{dede:global.cfg_basehost/}{dede:field name='typeurl'/}" title="{dede:field name='typename'/}">{dede:field name='typename'/}</a>
        	</li> 
			<div class="nav-down" id="nav-down-{dede:field name='id'/}" >
				<ul>
					<li><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></li>
					<li><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></li>
					<li><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></li>
					<li><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></li>
					<li><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></li>
					
				</ul>
			</div>