<?php
$z[0]=Array("global","",158,186);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("arcurl","",186,201);
$z[2]=Array("title","",226,240);
$z[3]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<img src='{@me['litpic']}'  />\"); ",266,376);
$z[3][4]['runphp']="yes";
$z[4]=Array("global","",440,468);
$z[4][4]['name']="cfg_basehost";
$z[5]=Array("arcurl","",468,483);
$z[6]=Array("title","",492,506);
$z[7]=Array("title","",524,538);

?>