<?php
$z[0]=Array("field","",15,38);
$z[0][4]['name']="id";
$z[1]=Array("global","",61,88);
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("field","",88,116);
$z[2][4]['name']="typeurl";
$z[3]=Array("field","",118,147);
$z[3][4]['name']="typename";
$z[4]=Array("field","",220,243);
$z[4][4]['name']="id";
$z[5]=Array("channel","\r\n					<li><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></li>\r\n					",263,414);
$z[5][4]['type']="son";
$z[5][4]['noself']="yes";
$z[6]=Array("field","",523,546);
$z[6][4]['name']="id";
$z[7]=Array("field","",618,641);
$z[7][4]['name']="id";

?>