<!-- list start -->
                <div class="list float-left">
                    <dl>
                    	<dt>
                    		[field:array runphp='yes']@me = (empty(@me['litpic']) ? "" : "<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>"); [/field:array]
                    	</dt>
                    	<dd><a href="" title="" target="_blank">[field:title/]</a></dd>
                    </dl>
                </div><!-- list end -->