<?php
$z[0]=Array("field","",15,38);
$z[0][4]['name']="id";
$z[1]=Array("global","",61,88);
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("field","",88,116);
$z[2][4]['name']="typeurl";
$z[3]=Array("field","",125,154);
$z[3][4]['name']="typename";
$z[4]=Array("field","",156,185);
$z[4][4]['name']="typename";
$z[5]=Array("channel","  \r\n			<div class=\"nav-down\" id=\"nav-down-[field:id/]\" >\r\n				<ul>\r\n					<li><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></li>\r\n				</ul>\r\n			</div>\r\n			",216,453);
$z[5][4]['type']="top";
$z[5][4]['noself']="yes";
$z[6]=Array("field","",535,558);
$z[6][4]['name']="id";
$z[7]=Array("field","",630,653);
$z[7][4]['name']="id";

?>