<!-- list start -->
                <div class="list float-left">
                    <dl>
                        <dt>
                            [field:array runphp='yes']@me = (empty(@me['litpic']) ? "" : "<img src='{@me['litpic']}' />"); [/field:array]
                        </dt>
                        <dd><a  target="_blank">[field:title/]</a></dd>
                    </dl>
                </div><!-- list end -->