<?php
$z[0]=Array("global","",15,42);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("field","",42,63);
$z[1][4]['name']="typeurl";
$z[2]=Array("php"," if(!\$GLOBALS['thisid']) echo \"class='active'\"; ",65,134);
$z[3]=Array("channel"," \r\n                    <span><a href='[field:global.cfg_basehost/][field:typelink/]' [field:rel/] [field:id runphp='yes'] if (@me == \$GLOBALS['thisid'] ) @me = \"class='active' \" ;[/field:id]>[field:typename/]</a></span> \r\n                ",176,554);
$z[3][4]['row']="9";
$z[3][4]['type']="son";
$z[3][4]['currentstyle']="<span><a href='~typelink~' class='active' [field:rel/]>~typename~</a></span>";

?>