<!-- list start -->
                <div class="list">
                    <div class="detail clear-width">
                        <div class="title">
                            <h2>
                                <a href="[field:global.cfg_basehost/][field:arcurl/]" title="[field:title/]" target="_blank">[field:title/]</a>
                            </h2>
                        </div>
                        <div class="des">
                            [field:description/]
                            <a href="[field:global.cfg_basehost/][field:arcurl/]"  title="[field:title/]" target="_blank"><详细介绍></a>
                        </div>
                        <div class="title">
                            <p class="info clear-text-align margin-top10">
                                <span>作者：[field:writer/]</span>
                                <span><a href="[field:typeurl/]">[field:typename/]</a></span>
                                <span>Tags：[field:id function=GetTags_list('@me')/]</span>
                                <span class="float-right">不看详细介绍了
								<a href="" class="go-on-ready" target="_blank"><直接下载></a>
                                </span>                                
                            </p>
                        </div>
                    </div>
                </div><!-- list end -->			
            </div><!-- left end -->

            <!-- right start -->
            <div class="right">
                <!-- side end -->
                <div class="side">
                    <div class="title">近期博客</div>
                    <div class="content">
                        <ul>
                            <li><h3><a href="">从微信消息说起，聊聊移动互联网下...</a></h3></li>
                            <li><h3><a href="">或多或少的都会看看网站是什么后才会...</a></h3></li>
                            <li><h3><a href="">的不安全性，用刚刚遇到的一个案例来...</a></h3></li>
                            <li><h3><a href="">信息安全这个话题被谈了多少年...</a></h3></li>
                            <li><h3><a href="">是个人都有了些许认知和了解，打开...</a></h3></li>
                            <li><h3><a href="">从微信消息说起，聊聊移动互联网下...</a></h3></li>
                            <li><h3><a href="">聊聊移动互联网下...</a></h3></li>
                            <li><h3><a href="">从微信消移动互刚的联网下刚遇到的...</a></h3></li>

                        </ul>
                    </div>
                    <p class="hr"></p>
                </div><!-- side end -->
                <!-- 文章分类 -->
                <div class="side">
                    <div class="title">文章分类</div>
                    <div class="content">
                        <ul>
                            <li><h3><a href="">从微信消息说起，聊聊移动互联网下...</a></h3></li>
                            <li><h3><a href="">或多或少的都会看看网站是什么后才会...</a></h3></li>
                            <li><h3><a href="">的不安全性，用刚刚遇到的一个案例来...</a></h3></li>
                            <li><h3><a href="">信息安全这个话题被谈了多少年...</a></h3></li>
                            <li><h3><a href="">是个人都有了些许认知和了解，打开...</a></h3></li>
                            <li><h3><a href="">从微信消息说起，聊聊移动互联网下...</a></h3></li>
                            <li><h3><a href="">聊聊移动互联网下...</a></h3></li>
                            <li><h3><a href="">从微信消移动互刚的联网下刚遇到的...</a></h3></li>

                        </ul>
                    </div>
                    <p class="hr"></p>
                </div><!-- 文章分类 结束 --> 
                <!-- count start -->
                <div class="count">
                    <div class="count-n">
                        <p>博客数：85</p>
                        <p>博客分类：12</p>
                        <p>工具：23</p>
                        <p>作品：5</p>
                        <p>访问：46384</p>
                    </div>
                </div><!-- count start -->
                <!-- 友好网站 start -->
                <div class="side">
                    <div class="count-n">
                        <div class="title clear-padding">友好网站</div>
                        <p><a href="">eoe安卓开发社区</a></p>
                        <p><a href="">程序员之家</a></p>
                        <p><a href="">百度联盟广告</a></p>
                        <p><a href="">作品：5</a></p>
                        <p><a href="">访问：46384</a></p>
                    </div>
                </div><!-- 友好网站 start -->
            </div><!-- right end -->
            <div class="clear"></div>
        </div>      	
    </div>

    <!-- footer staret -->
    {dede:include file='footer.htm'