<?php
$z[0]=Array("global","",231,259);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("arcurl","",259,274);
$z[2]=Array("title","",283,297);
$z[3]=Array("title","",315,329);
$z[4]=Array("description","",473,493);
$z[5]=Array("global","",532,560);
$z[5][4]['name']="cfg_basehost";
$z[6]=Array("arcurl","",560,575);
$z[7]=Array("title","",585,599);
$z[8]=Array("writer","",837,852);
$z[9]=Array("typeurl","",908,924);
$z[10]=Array("typename","",926,943);
$z[11]=Array("id","",1001,1041);
$z[11][4]['function']="GetTags_list('@me')";

?>