<?php
$z[0]=Array("global","",396,424);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("arcurl","",424,439);
$z[2]=Array("title","",448,462);
$z[3]=Array("title","",480,494);
$z[4]=Array("description","",638,658);
$z[5]=Array("global","",702,730);
$z[5][4]['name']="cfg_basehost";
$z[6]=Array("arcurl","",730,745);
$z[7]=Array("title","",774,788);
$z[8]=Array("writer","",1026,1041);
$z[9]=Array("typeurl","",1097,1113);
$z[10]=Array("typename","",1115,1132);
$z[11]=Array("id","",1190,1230);
$z[11][4]['function']="GetTags_list('@me')";

?>