<?php
$z[0]=Array("field","",15,38);
$z[0][4]['name']="id";
$z[1]=Array("global","",61,88);
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("field","",88,116);
$z[2][4]['name']="typeurl";
$z[3]=Array("field","",125,154);
$z[3][4]['name']="typename";
$z[4]=Array("field","",156,185);
$z[4][4]['name']="typename";
$z[5]=Array("field","",258,281);
$z[5][4]['name']="id";
$z[6]=Array("channel","\r\n					<li><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></li>\r\n					",301,452);
$z[6][4]['type']="son";
$z[6][4]['noself']="yes";
$z[7]=Array("field","",561,584);
$z[7][4]['name']="id";
$z[8]=Array("field","",656,679);
$z[8][4]['name']="id";

?>