<?php
$z[0]=Array("global","",231,259);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("arcurl","",259,274);
$z[2]=Array("title","",283,297);
$z[3]=Array("title","",315,329);
$z[4]=Array("description","",473,493);
$z[5]=Array("global","",537,565);
$z[5][4]['name']="cfg_basehost";
$z[6]=Array("arcurl","",565,580);
$z[7]=Array("title","",609,623);
$z[8]=Array("writer","",861,876);
$z[9]=Array("typeurl","",932,948);
$z[10]=Array("typename","",950,967);
$z[11]=Array("id","",1025,1065);
$z[11][4]['function']="GetTags_list('@me')";

?>