<?php
$z[0]=Array("global","",15,42);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("field","",42,63);
$z[1][4]['name']="typeurl";
$z[2]=Array("channel"," \r\n                    <span><a href='[field:global.cfg_basehost/][field:typelink/]' [field:rel/]>[field:typename/]</a></span> \r\n                ",121,393);
$z[2][4]['row']="9";
$z[2][4]['type']="son";
$z[2][4]['currentstyle']="<span><a href='~typelink~' class='active'>~typename~</a></span>";

?>