<?php
$z[0]=Array("global","",158,186);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("arcurl","",186,201);
$z[2]=Array("title","",226,240);
$z[3]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<img src='{@me['litpic']}' />\"); ",266,375);
$z[3][4]['runphp']="yes";
$z[4]=Array("global","",439,467);
$z[4][4]['name']="cfg_basehost";
$z[5]=Array("arcurl","",467,482);
$z[6]=Array("title","",491,505);
$z[7]=Array("title","",523,537);

?>