<?php
$z[0]=Array("link","",35,48);
$z[1]=Array("tag","",50,63);
$z[2]=Array("arcurl","",480,495);
$z[3]=Array("title","",497,511);
$z[4]=Array("click","",570,584);
$z[5]=Array("typelink","",1030,1047);
$z[6]=Array("typename","",1049,1066);
$z[7]=Array("id","",1404,1444);
$z[7][4]['function']="GetTotalArc(@me)";
$z[8]=Array("b-typenum","",1645,1663);
$z[9]=Array("id","",1796,1836);
$z[9][4]['function']="GetTotalArc(@me)";

?>