<!-- list start -->
                <div class="list float-left">
                    <dl>
                        <dt>
                            
                            [field:array runphp='yes']@me = (empty(@me['litpic']) ? "" : "<img src='{@me['litpic']}' />"); [/field:array]
                        </dt>
                        <dd>[field:title/]</dd>
                    </dl>
                </div><!-- list end -->