<!-- list start -->
                <div class="list float-left">
                    <dl>
                    	<dt>
                            <a href="[field:global.cfg_basehost/][field:arcurl/]" target="_blank" title="[field:title/]">
                    		[field:array runphp='yes']@me = (empty(@me['litpic']) ? "" : "<img src='{@me['litpic']}' alt="{@me['title']}" />"); [/field:array]
                    	</dt>
                    	<dd><a href="[field:global.cfg_basehost/][field:arcurl/]" title="[field:title/]" target="_blank">[field:title/]</a></dd>
                    </dl>
                </div><!-- list end -->