<?php
$z[0]=Array("global","",158,186);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("arcurl","",186,201);
$z[2]=Array("title","",226,240);
$z[3]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<img src='{@me['litpic']}' alt=\"{@me['title']}\" />\"); ",266,396);
$z[3][4]['runphp']="yes";
$z[4]=Array("global","",460,488);
$z[4][4]['name']="cfg_basehost";
$z[5]=Array("arcurl","",488,503);
$z[6]=Array("title","",512,526);
$z[7]=Array("title","",544,558);

?>