<?php
$z[0]=Array("global","",53,80);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("php"," if(\$refObj->Fields['id'] == 0){echo \"class='active'\";}",82,158);
$z[2]=Array("channel","\r\n            <li>\r\n            	<a href=\"[field:global.cfg_basehost/][field:typeurl/]\" [field:rel/] title=\"[field:typename/]\">[field:typename/]</a>\r\n            </li> \r\n        ",189,490);
$z[2][4]['row']="9";
$z[2][4]['type']="top";
$z[2][4]['currentstyle']="<li><a href='~typelink~' class=";
$z[2][4]['active">~typename~</a></li>"']="";
$z[3]=Array("channel"," \r\n			<li>\r\n				<a href='[field:global.cfg_basehost/][field:typelink/]' [field:rel/]>[field:typename/]</a> \r\n			</li> \r\n		",498,743);
$z[3][4]['row']="9";
$z[3][4]['type']="top";
$z[3][4]['currentstyle']="<li><a href='~typelink~' class='active'>~typename~</a></li>";
$z[4]=Array("channel","\r\n                               <li><a href=\"[field:global.cfg_basehost/][field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a></li> \r\n                               ",758,977);
$z[4][4]['type']="top";
$z[5]=Array("include","",1032,1062);
$z[5][4]['file']="rss.htm";
$z[6]=Array("php","\r\n	<!-- echo \"<pre/>\";\r\n	echo  intval(\$refObj->Fields['id']);\r\n	print_r(\$GLOBALS); -->\r\n",1064,1173);

?>