<?php
$z[0]=Array("arclist","\r\n                    <li>\r\n                        <a href=\"[field:arcurl/]\">[field:title/]</a> \r\n                        <span><small>人气:</small>[field:click/]</span>\r\n                    </li>\r\n                ",293,567);
$z[0][4]['flag']="c";
$z[0][4]['titlelen']="42";
$z[0][4]['row']="10";
$z[1]=Array("arclist","\r\n                    <li><h3><a href=\"[field:arcurl/]\">[field:title/]</a></h3></li>\r\n                ",840,992);
$z[1][4]['row']="10";
$z[1][4]['orderby']="click";

?>