<?php
$z[0]=Array("global","",236,271);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("global","",284,317);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",355,394);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",623,657);
$z[3][4]['name']="cfg_basehost";
$z[4]=Array("global","",723,752);
$z[4][4]['name']="maplist";
$z[5]=Array("include","",802,835);
$z[5][4]['file']="footer.htm";

?>