<?php
$z[0]=Array("global","",297,325);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("field","",338,361);
$z[1][4]['name']="seotitle";
$z[2]=Array("global","",362,388);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","",429,458);
$z[3][4]['name']="keywords";
$z[4]=Array("field","",498,556);
$z[4][4]['name']="description";
$z[4][4]['function']="html2text(@me)";
$z[5]=Array("global","",574,601);
$z[5][4]['name']="cfg_basehost";
$z[6]=Array("global","",601,633);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("global","",739,766);
$z[7][4]['name']="cfg_basehost";
$z[8]=Array("global","",766,798);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("global","",870,897);
$z[9][4]['name']="cfg_basehost";
$z[10]=Array("global","",897,929);
$z[10][4]['name']="cfg_templets_skin";
$z[11]=Array("include","",1037,1068);
$z[11][4]['file']="logo.htm";
$z[12]=Array("include","",1116,1147);
$z[12][4]['file']="head.htm";
$z[13]=Array("field","",1263,1285);
$z[13][4]['name']="position";
$z[14]=Array("sql","\r\n                        [field:body/]\r\n                    ",1694,1827);
$z[14][4]['sql']="select * from fang_addonarticle where aid=14";
$z[15]=Array("field","",1932,1953);
$z[15][4]['name']="content";
$z[16]=Array("include","",2586,2620);
$z[16][4]['file']="footer.htm";

?>