<?php
$z[0]=Array("global","",236,264);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("field","",277,296);
$z[1][4]['name']="title";
$z[2]=Array("global","",297,323);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","",364,393);
$z[3][4]['name']="keywords";
$z[4]=Array("field","",433,491);
$z[4][4]['name']="description";
$z[4][4]['function']="html2text(@me)";
$z[5]=Array("global","",509,536);
$z[5][4]['name']="cfg_basehost";
$z[6]=Array("global","",536,568);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("global","",652,679);
$z[7][4]['name']="cfg_basehost";
$z[8]=Array("global","",679,711);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("global","",839,866);
$z[9][4]['name']="cfg_basehost";
$z[10]=Array("global","",866,891);
$z[10][4]['name']="cfg_cmsurl";
$z[11]=Array("include","",1015,1050);
$z[11][4]['filename']="head.htm";
$z[12]=Array("tag","\r\n            <a href='[field:global.cfg_basehost/][field:link/]' class='tagc[field:highlight /]'>[field:tag /]</a>\r\n            ",1390,1560);
$z[12][4]['row']="60";
$z[12][4]['sort']="new";
$z[13]=Array("tag","\r\n            <a href='[field:global.cfg_basehost/][field:link/]' class='tagc[field:highlight /]'>[field:tag /]</a>\r\n            ",1838,2010);
$z[13][4]['row']="60";
$z[13][4]['sort']="month";
$z[14]=Array("tag","\r\n            <a href='[field:global.cfg_basehost/][field:link/]' class='tagc[field:highlight /]'>[field:tag /]</a>\r\n            ",2282,2454);
$z[14][4]['row']="100";
$z[14][4]['sort']="rand";
$z[15]=Array("include","",2507,2544);
$z[15][4]['filename']="footer.htm";

?>