<?php
$z[0]=Array("global","",297,325);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("field","",338,361);
$z[1][4]['name']="seotitle";
$z[2]=Array("global","",362,388);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","",429,458);
$z[3][4]['name']="keywords";
$z[4]=Array("field","",498,556);
$z[4][4]['name']="description";
$z[4][4]['function']="html2text(@me)";
$z[5]=Array("global","",602,629);
$z[5][4]['name']="cfg_basehost";
$z[6]=Array("global","",629,661);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("type","\r\n        <a href=\"[field:typelink/]\">返回[field:typename/]</a>\r\n        ",1052,1159);
$z[7][4]['typeid']="9";
$z[8]=Array("global","",1415,1442);
$z[8][4]['name']="cfg_basehost";
$z[9]=Array("global","",1442,1474);
$z[9][4]['name']="cfg_templets_skin";
$z[10]=Array("global","",2470,2497);
$z[10][4]['name']="cfg_basehost";
$z[11]=Array("global","",2497,2529);
$z[11][4]['name']="cfg_templets_skin";

?>